name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: setup
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: chmod
        run: chmod +x gradlew

      - name: decode build key
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > release-key.jks

      - name: build
        run: |
          ./gradlew assembleRelease \
          -Pandroid.injected.signing.store.file=$(pwd)/release-key.jks \
          -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }} \
          -Pandroid.injected.signing.key.alias=${{ secrets.KEY_ALIAS }} \
          -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}

      - name: 创建固定名称的最新版安装包
        run: cp "$(find app/build/outputs/apk/release -name '*.apk' -print -quit)" jm-rita-latest.apk

      - name: 自动创建 Release 并上传文件
        uses: softprops/action-gh-release@v2
        with:
          body: |
            详细变更请查看 [CHANGELOG](https://github.com/wt19980620-maker/jm-rita/blob/main/CHANGELOG.md) 。
          files: |
            app/build/outputs/apk/release/*.apk
            jm-rita-latest.apk
          generate_release_notes: false
          name: "Release ${{ github.ref_name }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
